//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tailspin.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tailspin.Model.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This credit card is invalid. Please check the expiration and card number..
        /// </summary>
        internal static string InvalidCreditCard {
            get {
                return ResourceManager.GetString("InvalidCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All orders must have a shipping address specified..
        /// </summary>
        internal static string NoAddress {
            get {
                return ResourceManager.GetString("NoAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No payment method is set for this order.
        /// </summary>
        internal static string NoPaymentMethod {
            get {
                return ResourceManager.GetString("NoPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cart item has a null Product.
        /// </summary>
        internal static string NullCartItemProduct {
            get {
                return ResourceManager.GetString("NullCartItemProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer cannot be null.
        /// </summary>
        internal static string NullCustomer {
            get {
                return ResourceManager.GetString("NullCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer cart cannot be null.
        /// </summary>
        internal static string NullCustomerCart {
            get {
                return ResourceManager.GetString("NullCustomerCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order must have one or more items.
        /// </summary>
        internal static string OrderZeroItems {
            get {
                return ResourceManager.GetString("OrderZeroItems", resourceCulture);
            }
        }
    }
}
