ALTER TABLE [dbo].[CartItems]
    ADD CONSTRAINT [PK_CartItems_1] PRIMARY KEY CLUSTERED ([SKU] ASC, [UserName] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

