ALTER TABLE [dbo].[Categories_Products]
    ADD CONSTRAINT [PK_Categories_Products] PRIMARY KEY CLUSTERED ([CategoryCode] ASC, [SKU] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

