ALTER TABLE [dbo].[InventoryStatus]
    ADD CONSTRAINT [PK_InventoryStatus] PRIMARY KEY CLUSTERED ([InventoryStatusID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

