ALTER TABLE [dbo].[OrderStatus]
    ADD CONSTRAINT [PK_OrderStatus] PRIMARY KEY CLUSTERED ([OrderStatusID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

