ALTER TABLE [dbo].[ProductDescriptors]
    ADD CONSTRAINT [PK_ProductDescriptors] PRIMARY KEY CLUSTERED ([DescriptorID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

