ALTER TABLE [dbo].[ProductImages]
    ADD CONSTRAINT [PK_ProductImages] PRIMARY KEY CLUSTERED ([ProductImageID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

