ALTER TABLE [dbo].[Products_Related]
    ADD CONSTRAINT [PK_Products_Related] PRIMARY KEY CLUSTERED ([SKU] ASC, [RelatedSKU] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

